[package]
name = "lc3vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
# libc = "0.2.112"
# signal-hook = "0.3.12"
# termios = "0.3.3"
